// DO NOT EDIT THIS FILE, IT IS AUTMATICALLY GENERATED

module.exports = function (blockly) {
	var Blockly = blockly.Blockly;
	// var goog = blockly.goog;

	Blockly.Blocks['adafruit_init_lcd'] = {
		init: function () {
			this.setHelpUrl('http://www.example.com/');
			this.setColour(260);
			this.appendDummyInput()
				.appendField('Init LCD Columns')
				.appendField(new Blockly.FieldDropdown([['16', '16'], ['20', '20']]), 'cols')
				.appendField('Rows')
				.appendField(new Blockly.FieldDropdown([['1', '1'], ['2', '2'], ['4', '4']]), 'rows');
			this.appendValueInput('rs')
				.setCheck('Number')
				.setAlign(Blockly.ALIGN_RIGHT)
				.appendField('RS Pin');
			this.appendValueInput('strobe')
				.setCheck('Number')
				.setAlign(Blockly.ALIGN_RIGHT)
				.appendField('Enable (E) Pin');
			this.appendValueInput('backlight')
				.setCheck('Number')
				.setAlign(Blockly.ALIGN_RIGHT)
				.appendField('Backlight Pin');
			this.appendValueInput('d0')
				.setCheck('Number')
				.setAlign(Blockly.ALIGN_RIGHT)
				.appendField('DB5');
			this.appendValueInput('d1')
				.setCheck('Number')
				.setAlign(Blockly.ALIGN_RIGHT)
				.appendField('DB6');
			this.appendValueInput('d2')
				.setCheck('Number')
				.setAlign(Blockly.ALIGN_RIGHT)
				.appendField('DB7');
			this.appendValueInput('d3')
				.setCheck('Number')
				.setAlign(Blockly.ALIGN_RIGHT)
				.appendField('DB8');
			this.setPreviousStatement(true);
			this.setNextStatement(true);
			this.setTooltip('');
		}
	};

	Blockly.Blocks['adafruit_clear_lcd'] = {
		init: function () {
			this.setHelpUrl('http://www.example.com/');
			this.setColour(260);
			this.appendDummyInput()
				.appendField('Clear LCD');
			this.setPreviousStatement(true);
			this.setNextStatement(true);
			this.setTooltip('');
		}
	};

	Blockly.Blocks['adafruit_reset_lcd'] = {
		init: function () {
			this.setHelpUrl('http://www.example.com/');
			this.setColour(260);
			this.appendDummyInput()
				.appendField('Reset Position on LCD');
			this.setPreviousStatement(true);
			this.setNextStatement(true);
			this.setTooltip('');
		}
	};

	Blockly.Blocks['adafruit_set_position_lcd'] = {
		init: function () {
			this.setHelpUrl('http://www.example.com/');
			this.setColour(260);
			this.appendDummyInput()
				.appendField('Set LCD Position');
			this.appendValueInput('col')
				.setCheck('Number')
				.appendField('Column');
			this.appendValueInput('row')
				.setCheck('Number')
				.appendField('Row');
			this.setInputsInline(true);
			this.setPreviousStatement(true);
			this.setNextStatement(true);
			this.setTooltip('');
		}
	};

	Blockly.Blocks['adafruit_print_lcd'] = {
		init: function () {
			this.setHelpUrl('http://www.example.com/');
			this.setColour(260);
			this.appendDummyInput()
				.appendField('Print on LCD');
			this.appendValueInput('text');
			this.setInputsInline(true);
			this.setPreviousStatement(true);
			this.setNextStatement(true);
			this.setTooltip('');
		}
	};

};