run:
	. .project/gitPrepare.sh
	echo "$(TOCK_LIBC_DIR)"
	rm -rf "$(TOCK_LIBC_DIR)/examples/studio"
	mkdir -p "$(TOCK_LIBC_DIR)/examples/studio"
	cp -R * "$(TOCK_LIBC_DIR)/examples/studio"
	cd "$(TOCK_LIBC_DIR)/examples/studio" && make -f Makefile.app
	. .project/upload.sh
	tockloader listen