// DO NOT EDIT THIS FILE, IT IS AUTMATICALLY GENERATED

module.exports = function (blockly) {
	var Blockly = blockly.Blockly;
	// var goog = blockly.goog;

	Blockly.Python.adafruit_dht_setup = function () {
		if (!Blockly.Python.definitions_['adafruit_dht_setup']) {
			Blockly.Python.definitions_['adafruit_dht_setup'] = 'import Adafruit_DHT \n';
		}
	};

	Blockly.Python['adafruit_dht_sensor_humidity'] = function (block) {
		Blockly.Python.adafruit_dht_setup ();
		var dropdown_sensor = block.getFieldValue('sensor');
		var value_pin = Blockly.Python.valueToCode(block, 'pin', Blockly.Python.ORDER_ATOMIC);
		// TODO: Assemble Python into code variable.
		var code = '(Adafruit_DHT.read_retry(' + dropdown_sensor.toString() + ', ' + value_pin.toString() + ')[0])';
		return [code, Blockly.Python.ORDER_NONE];
	};


	//TODO CHANGE TEMP
	Blockly.Python['adafruit_dht_sensor_temperature'] = function (block) {
		Blockly.Python.adafruit_dht_setup ();
		var dropdown_sensor = block.getFieldValue('sensor');
		var value_pin = Blockly.Python.valueToCode(block, 'pin', Blockly.Python.ORDER_ATOMIC);
		// TODO: Assemble Python into code variable.
		var code = '(Adafruit_DHT.read_retry(' + dropdown_sensor.toString() + ', ' + value_pin.toString() + ')[1])';
		return [code, Blockly.Python.ORDER_NONE];
	};
};