// DO NOT EDIT THIS FILE, IT IS AUTMATICALLY GENERATED

module.exports = function (blockly) {
	var Blockly = blockly.Blockly;
	// var goog = blockly.goog;

	Blockly.Python.micropython_import_Pin = function() {
		if (!Blockly.Python.definitions_['micropython_pin']) {
			Blockly.Python.definitions_['micropython_pin'] = 'from machine import Pin \n';
		}
	};

	Blockly.Python.micropython_import_PWM = function() {
		if (!Blockly.Python.definitions_['micropython_pwm']) {
			Blockly.Python.definitions_['micropython_pwm'] = 'from machine import PWM \n';
		}
	};

	Blockly.Python.micropython_import_time = function() {
		if (!Blockly.Python.definitions_['micropython_time']) {
			Blockly.Python.definitions_['micropython_time'] = 'import time \n';
		}
	};

	Blockly.Python.micropython_import_sleep_from_time = function() {
		if (!Blockly.Python.definitions_['micropython_sleep_from_time']) {
			Blockly.Python.definitions_['micropython_sleep_from_time'] = 'from time import sleep \n';
		}
	};

	Blockly.Python.micropython_import_utime = function() {
		if (!Blockly.Python.definitions_['micropython_utime']) {
			Blockly.Python.definitions_['micropython_utime'] = 'import utime \n';
		}
	};

	Blockly.Python.micropython_import_dht = function() {
		if (!Blockly.Python.definitions_['micropython_dht']) {
			Blockly.Python.definitions_['micropython_dht'] = 'import dht \n';
		}
	};
	
	Blockly.Python['micropython_pin'] = function(block) {
		Blockly.Python.micropython_import_Pin();
		var value_gpio = Blockly.Python.valueToCode(block, 'GPIO', Blockly.Python.ORDER_ATOMIC);
		var dropdown_type1 = block.getFieldValue('type1');
		var dropdown_type2 = block.getFieldValue('type2');
		// TODO: Assemble Python into code variable.
		var code = '';
		if(dropdown_type2.toString() == 'NONE') {
			code = 'Pin(' + value_gpio + ', ' + 'Pin.' + dropdown_type1 + ')'; //+ '\n';
		} else {
			code = 'Pin(' + value_gpio + ', ' + 'Pin.' + dropdown_type1 + ', ' + 'Pin.' + dropdown_type2 +')';// + '\n';
		}

		return [code, Blockly.Python.ORDER_NONE];
	};


	Blockly.Python['micropython_set_value'] = function(block) {
		var dropdown_set_value = block.getFieldValue('set_value');
		var value_pin_setvalue = Blockly.Python.valueToCode(block, 'pin_setValue', Blockly.Python.ORDER_ATOMIC);
		// TODO: Assemble Python into code variable.
		var code = value_pin_setvalue.toString() + '.value' + '(' + dropdown_set_value.toString() + ')' + '\n'; 
		return code;
	};

	Blockly.Python['micropython_get_value'] = function(block) {
		var value_get_value = Blockly.Python.valueToCode(block, 'get_value', Blockly.Python.ORDER_ATOMIC);
		// TODO: Assemble Python into code variable.
		var code = value_get_value.toString() + '.value()';
		// TODO: Change ORDER_NONE to the correct strength.
		return [code, Blockly.Python.ORDER_NONE];
	};

	Blockly.Python['micropython_on_off'] = function(block) {
		var dropdown_set_on_off = block.getFieldValue('set_on/off');
		var value_set_valueled = Blockly.Python.valueToCode(block, 'set_valueLED', Blockly.Python.ORDER_ATOMIC);
		// TODO: Assemble Python into code variable.
		var code = value_set_valueled.toString() + '.' + dropdown_set_on_off.toString() + '()' + '\n';
		return code;
	};

	Blockly.Python['micropython_pwm'] = function(block) {
		Blockly.Python.micropython_import_PWM();
		var value_pwm = Blockly.Python.valueToCode(block, 'pwm', Blockly.Python.ORDER_ATOMIC);
		var value_freq = Blockly.Python.valueToCode(block, 'freq', Blockly.Python.ORDER_ATOMIC);
		var value_duty = Blockly.Python.valueToCode(block, 'duty', Blockly.Python.ORDER_ATOMIC);
		// TODO: Assemble Python into code variable.
		var code = '';
		if (value_freq == 0 && value_duty == 0) {
			code = 'Pwm(' + value_pwm.toString() + ')' + '\n';
		} else if (value_duty == 0 && value_freq != 0){
			code = 'PWM(' + value_pwm.toString() + ', ' + 'freq=' + value_freq.toString() + ')' + '\n';
		} else if (value_freq == 0 && value_duty != 0) {
			code = 'PWM(' + value_pwm.toString() + ', ' + 'duty=' + value_duty.toString() + ')' + '\n';
		} else {
			code = 'PWM(' + value_pwm.toString() + ', ' + 'freq=' + value_freq.toString() + ', ' +'duty=' + value_duty.toString() + ')' + '\n';	
		}
		
		return [code, Blockly.Python.ORDER_NONE];
	};

	Blockly.Python['micropython_pwm_methods'] = function(block) {
		var dropdown_methods = block.getFieldValue('methods');
		var value_methods = Blockly.Python.valueToCode(block, 'methods', Blockly.Python.ORDER_ATOMIC);
		var value_name = Blockly.Python.valueToCode(block, 'NAME', Blockly.Python.ORDER_ATOMIC);
		// TODO: Assemble Python into code variable.
		var code = '';
		if (dropdown_methods.toString() === 'deinit') {
			code = value_name.toString() + '.' + dropdown_methods.toString() + '()' + '\n';
		} else {
			code = value_name.toString() + '.' + dropdown_methods.toString() + '(' + value_methods + ')' + '\n';
		}
	
		return code;
	};

	Blockly.Python['micropython_declaration_rgb_1'] = function(block) {
		var value_red = Blockly.Python.valueToCode(block, 'red', Blockly.Python.ORDER_ATOMIC);
		var value_green = Blockly.Python.valueToCode(block, 'green', Blockly.Python.ORDER_ATOMIC);
		var value_blue = Blockly.Python.valueToCode(block, 'blue', Blockly.Python.ORDER_ATOMIC);
		// TODO: Assemble Python into code variable.
		var code = 'red = ' + value_red.toString() + '\n' + 'green = ' + value_green.toString() + '\n' + 'blue = ' + value_blue.toString() + '\n';
		return code;
	};

	Blockly.Python['micropython_rgb_pwm_set'] = function(block) {
		var dropdown_rgb = block.getFieldValue('rgb');
		var text_duty = block.getFieldValue('duty');
		var value_name = Blockly.Python.valueToCode(block, 'NAME', Blockly.Python.ORDER_ATOMIC);
		// TODO: Assemble Python into code variable.
		var code = dropdown_rgb.toString() +'.' + text_duty.toString() + '(' + value_name + ')' + '\n';
		return code;
	};

	Blockly.Python['micropython_rgb_pin_set'] = function(block) {
		var dropdown_rgb = block.getFieldValue('rgb');
		var dropdown_func = block.getFieldValue('func');
		// TODO: Assemble Python into code variable.
		var code = dropdown_rgb.toString() + '.' + dropdown_func.toString() + '()' + '\n';
		return code;
	};

	Blockly.Python['micropython_time'] = function(block) {
		Blockly.Python.micropython_import_time();
		var dropdown_time = block.getFieldValue('time');
		var value_micropython_time = Blockly.Python.valueToCode(block, 'micropython_time', Blockly.Python.ORDER_ATOMIC);
		// TODO: Assemble Python into code variable.
		var code = 'time.' + dropdown_time.toString() + '(' + value_micropython_time + ')' + '\n';
		return code;
	};

	Blockly.Python['micropython_sleep_from_time'] = function(block) {
		Blockly.Python.micropython_import_sleep_from_time();
		var dropdown_unit_measurement = block.getFieldValue('unit_measurement');
		var value_micropython_sleep_from_time = Blockly.Python.valueToCode(block, 'micropython_sleep_from_time', Blockly.Python.ORDER_ATOMIC);
		// TODO: Assemble Python into code variable.
		var code = dropdown_unit_measurement.toString() + '(' + value_micropython_sleep_from_time + ')' + '\n';
		return code;
	};

	Blockly.Python['micropython_utime'] = function(block) {
		Blockly.Python.micropython_import_utime();
		var dropdown_utime = block.getFieldValue('utime');
		var value_micropython_utime = Blockly.Python.valueToCode(block, 'micropython_utime', Blockly.Python.ORDER_ATOMIC);
		// TODO: Assemble Python into code variable.
		var code = 'utime.' + dropdown_utime.toString() + '(' + value_micropython_utime + ')\n';
		return code;
	};

	Blockly.Python['micropython_machine_time_pulse_us'] = function(block) {
		var value_pin_var = Blockly.Python.valueToCode(block, 'pin/var', Blockly.Python.ORDER_ATOMIC);
		var dropdown_pulse = block.getFieldValue('pulse');
		var value_timeout_us = Blockly.Python.valueToCode(block, 'timeout_us', Blockly.Python.ORDER_ATOMIC);
		var value_var = Blockly.Python.valueToCode(block, 'var', Blockly.Python.ORDER_ATOMIC);
		// TODO: Assemble Python into code variable.
		var code = '';
		if (value_timeout_us == 0) {
			code = value_var.toString() + '=' + 'machine.time_pulse_us' + '(' + value_pin_var.toString() + ', ' + dropdown_pulse + ')' + '\n';
		} else {
			code = value_var.toString() + '=' + 'machine.time_pulse_us' + '(' + value_pin_var.toString() + ', ' + dropdown_pulse + ', ' + value_timeout_us + ')' + '\n';
		}
		return code;
	};

	Blockly.Python['micropython_adc'] = function(block) {
		var value_adc_var = Blockly.Python.valueToCode(block, 'adc_var', Blockly.Python.ORDER_ATOMIC);
		// TODO: Assemble Python into code variable.
		var code = 'ADC(' + value_adc_var + ')' + '\n';
		// TODO: Change ORDER_NONE to the correct strength.
		return [code, Blockly.Python.ORDER_NONE];
	};

	Blockly.Python['micropython_adc_method'] = function(block) {
		var value_name = Blockly.Python.valueToCode(block, 'NAME', Blockly.Python.ORDER_ATOMIC);
		// TODO: Assemble Python into code variable.
		var code = value_name.toString() + '.read()' + '\n';
		// TODO: Change ORDER_NONE to the correct strength.
		return [code, Blockly.Python.ORDER_NONE];
	};

	Blockly.Python['micropython_adc_pin'] = function(block) {
		var value_adc_pin = Blockly.Python.valueToCode(block, 'adc_pin', Blockly.Python.ORDER_ATOMIC);
		// TODO: Assemble Python into code variable.
		var code = 'ADC' + value_adc_pin + '\n';
		// TODO: Change ORDER_NONE to the correct strength.
		return [code, Blockly.Python.ORDER_NONE];
	};
	
	Blockly.Python['micropython_print'] = function(block) {
		var value_print_value = Blockly.Python.valueToCode(block, 'print_value', Blockly.Python.ORDER_ATOMIC);
		// TODO: Assemble Python into code variable.
		var code = 'print(' + value_print_value + ')\n';
		// if (isNaN(value_print_value)) {
		// 	code = 'print("' + value_print_value.toString() + '")\n';
		// } else {
		// 	code = 'print(' + value_print_value + ')\n';
		// }
		
		return code;
	};

	Blockly.Python['micropython_print_format'] = function(block) {
		var text_quotation_mark = block.getFieldValue('text_quotation_mark');
		var value_var1 = Blockly.Python.valueToCode(block, 'var1', Blockly.Python.ORDER_ATOMIC);
		var value_var2 = Blockly.Python.valueToCode(block, 'var2', Blockly.Python.ORDER_ATOMIC);
		var value_var3 = Blockly.Python.valueToCode(block, 'var3', Blockly.Python.ORDER_ATOMIC);
		// TODO: Assemble Python into code variable.
		var code = '';
		if (value_var1 && value_var2 && value_var3) {
			code = 'print("' + text_quotation_mark.toString() + '")' + '.format(' + value_var1.toString() + ',' + value_var2.toString() + ',' + value_var3.toString() + ')' +')\n';
		} else if (value_var1 && value_var2) {
			code = 'print("' + text_quotation_mark.toString() + '")' + '.format(' + value_var1.toString() + ',' + value_var2.toString() + ')' +')\n';
		} else if (value_var1 && value_var3) {
			code = 'print("' + text_quotation_mark.toString() + '")' + '.format(' + value_var1.toString() + ',' + value_var3.toString() + ')' +')\n';
		} else if (value_var2 && value_var3) {
			code = 'print("' + text_quotation_mark.toString() + '")' + '.format('  + value_var2.toString() + ',' + value_var3.toString() + ')' +')\n';
		} else if (value_var1) {
			code = 'print("' + text_quotation_mark.toString() + '")' + '.format(' + value_var1.toString() + ')' +')\n';
		} else if (value_var2) {
			code = 'print("' + text_quotation_mark.toString() + '")' + '.format(' + value_var2.toString() + ')' +')\n';
		} else if (value_var3) {
			code = 'print("' + text_quotation_mark.toString() + '")' + '.format(' + value_var3.toString() + ')' +')\n';
		}
		return code;
	};

	Blockly.Python['micropython_dht'] = function(block) {
		Blockly.Python.micropython_import_dht();
		var value_dht = Blockly.Python.valueToCode(block, 'dht', Blockly.Python.ORDER_ATOMIC);
		// TODO: Assemble Python into code variable.
		var code = 'dht.DHT11' + value_dht.toString();
		// TODO: Change ORDER_NONE to the correct strength.
		return [code, Blockly.Python.ORDER_NONE];
	};

	Blockly.Python['micropython_dht_sensors'] = function(block) {
		var dropdown_sensors = block.getFieldValue('sensors');
		var value_sensors = Blockly.Python.valueToCode(block, 'sensors', Blockly.Python.ORDER_ATOMIC);
		// TODO: Assemble Python into code variable.
		var code =value_sensors.toString() + '.' + dropdown_sensors.toString() + '()' +'\n'  ;
		return code;
	};

	Blockly.Python['micropython_get_dht_sensors'] = function(block) {
		var dropdown_sensors = block.getFieldValue('sensors');
		var value_get_value_sensor = Blockly.Python.valueToCode(block, 'get_value_sensor', Blockly.Python.ORDER_ATOMIC);
		// TODO: Assemble Python into code variable.
		var code = '';
		if (value_get_value_sensor) {
			code = value_get_value_sensor.toString() + '.' + dropdown_sensors.toString() + '()';
		} else {
			code = dropdown_sensors.toString() + '()' + '\n';
		}
		// TODO: Change ORDER_NONE to the correct strength.
		return [code, Blockly.Python.ORDER_NONE];
	};

	Blockly.Python['micropython_try_catch'] = function(block) {
		var statements_try_catch = Blockly.Python.statementToCode(block, 'try_catch');
		var text_error = block.getFieldValue('error');
		var value_except = Blockly.Python.valueToCode(block, 'except', Blockly.Python.ORDER_ATOMIC);
		var statements_except_code = Blockly.Python.statementToCode(block, 'except_code');
		// TODO: Assemble Python into code variable.
		var code = 'try:' + '\n' + statements_try_catch + 'except ' + text_error.toString() + ' as ' + value_except.toString() + ':' + '\n' + statements_except_code + '\n';
		return code;
	};
};