module.exports = [
	"I think my neighbor is stalking me as she's been googling my name on her computer. I saw it through my telescope last night.",
	"I changed my password to \"incorrect\". So whenever I forget what it is the computer will say \"Your password is incorrect\".",
	"Entered what I ate today into my new fitness app and it just sent an ambulance to my house.",
	"A clean house is the sign of a broken computer.",
	"Wifi went down during family dinner tonight. One kid started talking and I didn't know who he was.",
	"A TV can insult your intelligence, but nothing rubs it in like a computer.",
	"A computer once beat me at chess, but it was no match for me at kick boxing.",
	"Any room is a panic room if you've lost your phone in it.",
	"My internet is so slow, it's just faster to drive to the Google headquarters and ask them things in person.",
	"Autocorrect just changed &quot;I have so much anxiety I can barely breathe&quot; to &quot;I'm fine.&quot;",
	"What was Forrest Gump's email password? \"1forrest1\"",
	"I would like to thank everybody that stuck by my side for those five long minutes my house didn't have internet.",
	"Waitress: 'Do u have any questions about the menu?' Me: 'What kind of font is this?'",
	"Are you a computer whiz? it seems you know how to turn my software to hardware.",
	"Failure is not an option—it comes bundled with the software.",
	"It's ok computer, I go to sleep after 20 minutes of inactivity too.",
	"I just want to live in a world where people come with on/off switches.",
	"You'd think that with NSA reading our tweets all the time, they could star or retweet some of the good ones.",
	"Is your name Wi-Fi? Because I'm feeling a connection.",
	"What does a baby computer call its father? Data.",
	"It's okay Microsoft Excel even my love life is not responding.",
	"Are you a keyboard? Because you're my type!",
	"I used to think love() was abstract, until you implemented it in MyHeart.",
	"Smartphones are pacifiers for adults.",
	"Every function without you will always be void of love.",
	"I buy a lot of ringtones for someone who hasn't answered a phone call since 2008.",
	"We just got a fax. At work. We didn't know we had a fax machine. The entire department just stared at it. I poked it with a stick.",
	"I love the F5 key. It´s just so refreshing.",
	"HOW DO I TURN OFF CAPS LOCK? I ACCIDENTALLY TURNED IT ON YESTERDAY AND I DON'T KNOW HOW TO TURN IT BACK OFF. ALL MY FRIENDS ARE MAD BECAUSE THEY THINK I AM SHOUTING AT THEM OVER INTERNET. PLEASE HELP!!!",
	"This must be the 8th castle because I just found my princess.",
	"Roses are #FF0000, violets are #0000FF. All my base are belong to you.",
	"I downloaded the Pinterest app and now my phone is stuck in a mason jar.",
	"The first time I got a universal remote control, I thought to myself &quot;This changes everything&quot;.",
	"My New Years resolution is 1080p.",
	"If Bill Gates had a penny for every time I had to reboot my computer ...oh wait, he does.",
	"My voicemail message is just instructions on how to send a text message with brief pauses filled with heavy sighing.",
	"How do we not know what women want yet? There are tons of conflicting lists all over the internet.",
	"Baby you're so cute you made my page 404.",
	"If you were a browser, you'd be called FireFoxy.",
	"Getting a red heart instead of a yellow star makes me feel like things are moving a little too fast between us.",
	"Facebook is telling me to &quot;reconnect&quot; with my brother...hmmm, I see him everyday",
	"Twitter is just LinkedIn for the chronically unemployed.",
	"You have the nicest syntax I've ever seen.",
	"*Puts down phone* OH MY GOD I HAVE ANOTHER HAND!",
	"You are one well-defined function!",
	"Wow, this article looks awesome.    *clicks link*    *finds out it's a slideshow*    *throws computer out the window*",
	"If I was an operating system, your process would have top priority.",
	"Computer does what you command him to do but not what you want from him.",
	"You are my methods. I am nothing without you.",
	"I need more than 140 characters to tell you how beautiful you are.",
	"How good are you at powerpoint? I Excel at it!",
	"If I freeze, it's not a computer virus. I was just stunned by your beauty.",
	"Ready for the only way to enjoy Instagram? Follow zero people. Follow every dog.",
	"If I can't buy you a drink, at least let me fix your laptop.",
	"Are you an exception? I bet I can catch you."
];