// DO NOT EDIT THIS FILE, IT IS AUTMATICALLY GENERATED

module.exports = function (blockly) {
	var Blockly = blockly.Blockly;
	// var goog = blockly.goog;

	Blockly.Blocks['adafruit_dht_sensor_humidity'] = {
		init: function() {
			this.appendValueInput('pin')
				.appendField(new Blockly.FieldDropdown([
					['DHT 11', 'Adafruit_DHT.DHT11'],
					['DHT 22', 'Adafruit_DHT.DHT22'],
					['AM 2302', 'Adafruit_DHT.AM2302'],
				]), 'sensor')
				.setCheck(['String', 'Number'])
				.appendField('Temperature sensor');
			this.setOutput(true, 'Number');
			this.setColour(120);
			this.setTooltip('');
			this.setHelpUrl('');
		}
	};

	Blockly.Blocks['adafruit_dht_sensor_temperature'] = {
		init: function() {
			this.appendValueInput('pin')
				.appendField(new Blockly.FieldDropdown([
					['DHT 11', 'Adafruit_DHT.DHT11'],
					['DHT 22', 'Adafruit_DHT.DHT22'],
					['AM 2302', 'Adafruit_DHT.AM2302'],
				]), 'sensor')
				.setCheck(['String', 'Number'])
				.appendField('Humidity sensor');
			this.setOutput(true, 'Number');
			this.setColour(120);
			this.setTooltip('');
			this.setHelpUrl('');
		}
	};

};